# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Copy requirements files
COPY pyproject.toml .

# Install pip tools
RUN pip install --upgrade pip

# Install dependencies
# Using pip install with extras for mcp since no poetry file is provided
RUN pip install "mcp[cli]>=1.6.0" loguru yfinance

# Copy project files
COPY . .

# Expose port if needed (not required for stdio transport) 

# Default command
CMD ["python", "mcp_server_yfinance/server.py"]
